# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date_of_event', models.DateField()),
                ('time_of_event', models.CharField(choices=[(b'', b'Hour of Event'), (b'12 PM', b'12 PM'), (b'01 PM', b'01 PM'), (b'02 PM', b'02 PM'), (b'03 PM', b'03 PM'), (b'04 PM', b'04 PM'), (b'05 PM', b'05 PM'), (b'06 PM', b'06 PM'), (b'07 PM', b'07 PM'), (b'08 PM', b'08 PM'), (b'09 PM', b'09 PM'), (b'10 PM', b'10 PM'), (b'11 PM', b'11 PM'), (b'12 AM', b'12 AM'), (b'01 AM', b'01 AM'), (b'02 AM', b'02 AM'), (b'03 AM', b'03 AM'), (b'04 AM', b'04 AM'), (b'05 AM', b'05 AM'), (b'06 AM', b'06 AM'), (b'07 AM', b'07 AM'), (b'08 AM', b'08 AM'), (b'09 AM', b'09 AM'), (b'10 AM', b'10 AM'), (b'11 AM', b'11 AM')], max_length=40)),
                ('event_location', models.CharField(choices=[(b'', b'Where is the event located?'), (b'Chapter House', b'Chapter House'), (b'Other Campus Venue', b'Other Campus Venue'), (b'Off Campus', b'Off Campus')], max_length=100)),
                ('event_location_other', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_planner', models.CharField(max_length=100)),
                ('phone_number_of_planner', models.CharField(max_length=40)),
                ('email_of_planner', models.CharField(max_length=40)),
                ('expected_number_guests', models.IntegerField()),
                ('affiliated_council', models.CharField(choices=[(b'', b'Affiliated Council'), (b'Interfraternity Council', b'Interfraternity Council'), (b'Panhellenic', b'Panhellenic'), (b'NPHC', b'NPHC'), (b'Non-Affiliated', b'Non-Affiliated')], max_length=40)),
                ('type_of_event', models.CharField(choices=[(b'', b'Type of Event'), (b'Social', b'Social'), (b'Date Function', b'Date Function'), (b'Formal', b'Formal'), (b'Other', b'Other')], max_length=40)),
                ('type_event_other', models.CharField(blank=True, max_length=100, null=True)),
                ('event_description', models.TextField()),
                ('invitation_type', models.CharField(choices=[(b'', b'Choose One'), (b'Invitation Only', b'Invitation Only'), (b'Open to the Public', b'Open to the Public'), (b'Open to Faculty, Staff, Students', b'Open to Faculty, Staff, Students')], max_length=100)),
                ('transportation', models.TextField(blank=True, null=True)),
                ('one_entry_point', models.CharField(choices=[(b'', b'Will there be one entry point?'), (b'Yes', b'Yes'), (b'No', b'No')], max_length=10)),
                ('entry_point_location', models.CharField(max_length=100)),
                ('co_sponsored_description', models.TextField(blank=True, null=True)),
                ('alcohol_distribution', models.TextField(blank=True, null=True)),
                ('sober_monitors', models.TextField()),
                ('presidents_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[(b'', b'Select severity of violation'), (b'Low', b'Low'), (b'Medium', b'Medium'), (b'High', b'High')], max_length=10)),
                ('category', models.CharField(choices=[(b'', b'Select category for flag'), (b'Underage Drinking', b'Underage Drinking'), (b'Stealing', b'Stealing'), (b'Vandalism', b'Vandalism'), (b'Violence', b'Violence'), (b'Other', b'Other')], max_length=20)),
                ('other_description', models.CharField(blank=True, help_text=b'If you chose other, fill in description', max_length=30, null=True)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=10)),
                ('event', models.ManyToManyField(to='main.Event')),
            ],
        ),
        migrations.CreateModel(
            name='GuestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'images/guests')),
                ('image_thumb', models.ImageField(upload_to=b'images/guests')),
                ('date_time_taken', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('acronym', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Organization'),
        ),
        migrations.AddField(
            model_name='host',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.University'),
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flag',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Guest'),
        ),
        migrations.AddField(
            model_name='flag',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Host'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Host'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.University'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
